// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    public static var point: Point {
        Point(path: "/weather/point")
    }

    public struct Point {
        /// Path: `/weather/point`
        public let path: String

        /// Get weather data for a specific point
        public func get(parameters: GetParameters) -> Request<GetResponse> {
            Request(path: path, method: "GET", query: parameters.asQuery)
        }

        public struct GetResponse: Decodable {
            public var meta: Meta?
            public var data: [Datum]?

            public struct Meta: Decodable {
                public var latitude: Double?
                public var longitude: Double?
                public var dailyQuota: Int?
                public var requestsMade: Int?

                public init(latitude: Double? = nil, longitude: Double? = nil, dailyQuota: Int? = nil, requestsMade: Int? = nil) {
                    self.latitude = latitude
                    self.longitude = longitude
                    self.dailyQuota = dailyQuota
                    self.requestsMade = requestsMade
                }

                public init(from decoder: Decoder) throws {
                    let values = try decoder.container(keyedBy: StringCodingKey.self)
                    self.latitude = try values.decodeIfPresent(Double.self, forKey: "latitude")
                    self.longitude = try values.decodeIfPresent(Double.self, forKey: "longitude")
                    self.dailyQuota = try values.decodeIfPresent(Int.self, forKey: "dailyQuota")
                    self.requestsMade = try values.decodeIfPresent(Int.self, forKey: "requestsMade")
                }
            }

            public struct Datum: Decodable {
                public var time: String?
                public var airTemperature: [String: String]?
                public var airTemperature80m: [String: String]?
                public var airTemperature100m: [String: String]?
                public var airTemperature1000hpa: [String: String]?
                public var airTemperature800hpa: [String: String]?
                public var airTemperature500hpa: [String: String]?
                public var airTemperature200hpa: [String: String]?
                public var pressure: [String: String]?
                public var cloudCover: [String: String]?
                public var currentDirection: [String: String]?
                public var currentSpeed: [String: String]?
                public var gust: [String: String]?
                public var humidity: [String: String]?
                public var iceCover: [String: String]?
                public var precipitation: [String: String]?
                public var snowDepth: [String: String]?
                public var seaLevel: [String: String]?
                public var swellDirection: [String: String]?
                public var swellHeight: [String: String]?
                public var swellPeriod: [String: String]?
                public var secondarySwellPeriod: [String: String]?
                public var secondarySwellDirection: [String: String]?
                public var secondarySwellHeight: [String: String]?
                public var visibility: [String: String]?
                public var waterTemperature: [String: String]?
                public var waveDirection: [String: String]?
                public var waveHeight: [String: String]?
                public var wavePeriod: [String: String]?
                public var windWaveDirection: [String: String]?
                public var windWaveHeight: [String: String]?
                public var windDirection1000hpa: [String: String]?
                public var windDirection800hpa: [String: String]?
                public var windDirection500hpa: [String: String]?
                public var windDirection200hpa: [String: String]?
                public var windSpeed: [String: String]?
                public var windSpeed20m: [String: String]?
                public var windSpeed30m: [String: String]?
                public var windSpeed40m: [String: String]?
                public var windSpeed50m: [String: String]?
                public var windSpeed80m: [String: String]?

                public init(time: String? = nil, airTemperature: [String: String]? = nil, airTemperature80m: [String: String]? = nil, airTemperature100m: [String: String]? = nil, airTemperature1000hpa: [String: String]? = nil, airTemperature800hpa: [String: String]? = nil, airTemperature500hpa: [String: String]? = nil, airTemperature200hpa: [String: String]? = nil, pressure: [String: String]? = nil, cloudCover: [String: String]? = nil, currentDirection: [String: String]? = nil, currentSpeed: [String: String]? = nil, gust: [String: String]? = nil, humidity: [String: String]? = nil, iceCover: [String: String]? = nil, precipitation: [String: String]? = nil, snowDepth: [String: String]? = nil, seaLevel: [String: String]? = nil, swellDirection: [String: String]? = nil, swellHeight: [String: String]? = nil, swellPeriod: [String: String]? = nil, secondarySwellPeriod: [String: String]? = nil, secondarySwellDirection: [String: String]? = nil, secondarySwellHeight: [String: String]? = nil, visibility: [String: String]? = nil, waterTemperature: [String: String]? = nil, waveDirection: [String: String]? = nil, waveHeight: [String: String]? = nil, wavePeriod: [String: String]? = nil, windWaveDirection: [String: String]? = nil, windWaveHeight: [String: String]? = nil, windDirection1000hpa: [String: String]? = nil, windDirection800hpa: [String: String]? = nil, windDirection500hpa: [String: String]? = nil, windDirection200hpa: [String: String]? = nil, windSpeed: [String: String]? = nil, windSpeed20m: [String: String]? = nil, windSpeed30m: [String: String]? = nil, windSpeed40m: [String: String]? = nil, windSpeed50m: [String: String]? = nil, windSpeed80m: [String: String]? = nil) {
                    self.time = time
                    self.airTemperature = airTemperature
                    self.airTemperature80m = airTemperature80m
                    self.airTemperature100m = airTemperature100m
                    self.airTemperature1000hpa = airTemperature1000hpa
                    self.airTemperature800hpa = airTemperature800hpa
                    self.airTemperature500hpa = airTemperature500hpa
                    self.airTemperature200hpa = airTemperature200hpa
                    self.pressure = pressure
                    self.cloudCover = cloudCover
                    self.currentDirection = currentDirection
                    self.currentSpeed = currentSpeed
                    self.gust = gust
                    self.humidity = humidity
                    self.iceCover = iceCover
                    self.precipitation = precipitation
                    self.snowDepth = snowDepth
                    self.seaLevel = seaLevel
                    self.swellDirection = swellDirection
                    self.swellHeight = swellHeight
                    self.swellPeriod = swellPeriod
                    self.secondarySwellPeriod = secondarySwellPeriod
                    self.secondarySwellDirection = secondarySwellDirection
                    self.secondarySwellHeight = secondarySwellHeight
                    self.visibility = visibility
                    self.waterTemperature = waterTemperature
                    self.waveDirection = waveDirection
                    self.waveHeight = waveHeight
                    self.wavePeriod = wavePeriod
                    self.windWaveDirection = windWaveDirection
                    self.windWaveHeight = windWaveHeight
                    self.windDirection1000hpa = windDirection1000hpa
                    self.windDirection800hpa = windDirection800hpa
                    self.windDirection500hpa = windDirection500hpa
                    self.windDirection200hpa = windDirection200hpa
                    self.windSpeed = windSpeed
                    self.windSpeed20m = windSpeed20m
                    self.windSpeed30m = windSpeed30m
                    self.windSpeed40m = windSpeed40m
                    self.windSpeed50m = windSpeed50m
                    self.windSpeed80m = windSpeed80m
                }

                public init(from decoder: Decoder) throws {
                    let values = try decoder.container(keyedBy: StringCodingKey.self)
                    self.time = try values.decodeIfPresent(String.self, forKey: "time")
                    self.airTemperature = try values.decodeIfPresent([String: String].self, forKey: "airTemperature")
                    self.airTemperature80m = try values.decodeIfPresent([String: String].self, forKey: "airTemperature80m")
                    self.airTemperature100m = try values.decodeIfPresent([String: String].self, forKey: "airTemperature100m")
                    self.airTemperature1000hpa = try values.decodeIfPresent([String: String].self, forKey: "airTemperature1000hpa")
                    self.airTemperature800hpa = try values.decodeIfPresent([String: String].self, forKey: "airTemperature800hpa")
                    self.airTemperature500hpa = try values.decodeIfPresent([String: String].self, forKey: "airTemperature500hpa")
                    self.airTemperature200hpa = try values.decodeIfPresent([String: String].self, forKey: "airTemperature200hpa")
                    self.pressure = try values.decodeIfPresent([String: String].self, forKey: "pressure")
                    self.cloudCover = try values.decodeIfPresent([String: String].self, forKey: "cloudCover")
                    self.currentDirection = try values.decodeIfPresent([String: String].self, forKey: "currentDirection")
                    self.currentSpeed = try values.decodeIfPresent([String: String].self, forKey: "currentSpeed")
                    self.gust = try values.decodeIfPresent([String: String].self, forKey: "gust")
                    self.humidity = try values.decodeIfPresent([String: String].self, forKey: "humidity")
                    self.iceCover = try values.decodeIfPresent([String: String].self, forKey: "iceCover")
                    self.precipitation = try values.decodeIfPresent([String: String].self, forKey: "precipitation")
                    self.snowDepth = try values.decodeIfPresent([String: String].self, forKey: "snowDepth")
                    self.seaLevel = try values.decodeIfPresent([String: String].self, forKey: "seaLevel")
                    self.swellDirection = try values.decodeIfPresent([String: String].self, forKey: "swellDirection")
                    self.swellHeight = try values.decodeIfPresent([String: String].self, forKey: "swellHeight")
                    self.swellPeriod = try values.decodeIfPresent([String: String].self, forKey: "swellPeriod")
                    self.secondarySwellPeriod = try values.decodeIfPresent([String: String].self, forKey: "secondarySwellPeriod")
                    self.secondarySwellDirection = try values.decodeIfPresent([String: String].self, forKey: "secondarySwellDirection")
                    self.secondarySwellHeight = try values.decodeIfPresent([String: String].self, forKey: "secondarySwellHeight")
                    self.visibility = try values.decodeIfPresent([String: String].self, forKey: "visibility")
                    self.waterTemperature = try values.decodeIfPresent([String: String].self, forKey: "waterTemperature")
                    self.waveDirection = try values.decodeIfPresent([String: String].self, forKey: "waveDirection")
                    self.waveHeight = try values.decodeIfPresent([String: String].self, forKey: "waveHeight")
                    self.wavePeriod = try values.decodeIfPresent([String: String].self, forKey: "wavePeriod")
                    self.windWaveDirection = try values.decodeIfPresent([String: String].self, forKey: "windWaveDirection")
                    self.windWaveHeight = try values.decodeIfPresent([String: String].self, forKey: "windWaveHeight")
                    self.windDirection1000hpa = try values.decodeIfPresent([String: String].self, forKey: "windDirection1000hpa")
                    self.windDirection800hpa = try values.decodeIfPresent([String: String].self, forKey: "windDirection800hpa")
                    self.windDirection500hpa = try values.decodeIfPresent([String: String].self, forKey: "windDirection500hpa")
                    self.windDirection200hpa = try values.decodeIfPresent([String: String].self, forKey: "windDirection200hpa")
                    self.windSpeed = try values.decodeIfPresent([String: String].self, forKey: "windSpeed")
                    self.windSpeed20m = try values.decodeIfPresent([String: String].self, forKey: "windSpeed20m")
                    self.windSpeed30m = try values.decodeIfPresent([String: String].self, forKey: "windSpeed30m")
                    self.windSpeed40m = try values.decodeIfPresent([String: String].self, forKey: "windSpeed40m")
                    self.windSpeed50m = try values.decodeIfPresent([String: String].self, forKey: "windSpeed50m")
                    self.windSpeed80m = try values.decodeIfPresent([String: String].self, forKey: "windSpeed80m")
                }
            }

            public init(meta: Meta? = nil, data: [Datum]? = nil) {
                self.meta = meta
                self.data = data
            }

            public init(from decoder: Decoder) throws {
                let values = try decoder.container(keyedBy: StringCodingKey.self)
                self.meta = try values.decodeIfPresent(Meta.self, forKey: "meta")
                self.data = try values.decodeIfPresent([Datum].self, forKey: "data")
            }
        }

        public struct GetParameters {
            public var lat: Double
            public var lng: Double
            public var params: String
            public var start: Int?
            public var end: Int?
            public var source: String?

            public init(lat: Double, lng: Double, params: String, start: Int? = nil, end: Int? = nil, source: String? = nil) {
                self.lat = lat
                self.lng = lng
                self.params = params
                self.start = start
                self.end = end
                self.source = source
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(lat, forKey: "lat")
                encoder.encode(lng, forKey: "lng")
                encoder.encode(params, forKey: "params")
                encoder.encode(start, forKey: "start")
                encoder.encode(end, forKey: "end")
                encoder.encode(source, forKey: "source")
                return encoder.items
            }
        }
    }
}
